spring.application.name=Shopstack-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/shopstack_db
spring.datasource.username=postgres
spring.datasource.password=Avengers@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

razorpay.key.id=rzp_test_TPYmZHtZ94GGNi
razorpay.key.secret=Re0v2zLw3Xn447DXgtNNezdC
shopstack.commission.rate=10