import React, { useEffect, useState } from "react";
import axios from "axios";

const API = import.meta.env.VITE_API_BASE_URL;
const empty = { name:"", code:"", address:"", city:"", state:"", pincode:"", active:true };

export default function AdminWarehouses(){
    const token=localStorage.getItem("token");
    const [warehouses,setWarehouses]=useState([]), [form,setForm]=useState(empty), [editing,setEditing]=useState(null);
    const [inventory,setInventory]=useState([]), [products,setProducts]=useState([]), [selectedWarehouse,setSelectedWarehouse]=useState("");
    const [productId,setProductId]=useState(""), [quantity,setQuantity]=useState(0), [message,setMessage]=useState("");
    const headers={Authorization:`Bearer ${token}`};
    const load=async()=>{try{const [w,i,p]=await Promise.all([axios.get(`${API}/api/admin/warehouses`,{headers}),axios.get(`${API}/api/admin/warehouses/inventory`,{headers}),axios.get(`${API}/api/products`)]);setWarehouses(w.data);setInventory(i.data);setProducts(p.data||[]);}catch(e){setMessage(e.response?.data||"Failed to load warehouse data");}};
    useEffect(()=>{load()},[]);
    const submit=async e=>{e.preventDefault();try{if(editing) await axios.put(`${API}/api/admin/warehouses/${editing}`,form,{headers}); else await axios.post(`${API}/api/admin/warehouses`,form,{headers});setForm(empty);setEditing(null);setMessage("Warehouse saved");load();}catch(e){setMessage(e.response?.data||"Unable to save warehouse");}};
    const remove=async id=>{if(!window.confirm("Delete this warehouse?"))return;try{await axios.delete(`${API}/api/admin/warehouses/${id}`,{headers});load();}catch(e){setMessage(e.response?.data||"Warehouse cannot be deleted");}};
    const saveStock=async e=>{e.preventDefault();try{await axios.put(`${API}/api/admin/warehouses/${selectedWarehouse}/inventory`,{productId:Number(productId),quantity:Number(quantity)},{headers});setMessage("Inventory updated");load();}catch(e){setMessage(e.response?.data||"Unable to update inventory");}};
    return <div className="min-h-screen bg-gray-100 p-8"><div className="max-w-7xl mx-auto"><h1 className="text-3xl font-bold mb-6">Warehouse Management</h1>{message&&<div className="mb-4 p-3 bg-blue-100 rounded">{message}</div>}
        <div className="grid md:grid-cols-2 gap-6 mb-8"><form onSubmit={submit} className="bg-white p-6 rounded-xl shadow space-y-3"><h2 className="text-xl font-semibold">{editing?"Edit Warehouse":"Add Warehouse"}</h2>{["name","code","address","city","state","pincode"].map(k=><input key={k} required={k==="name"||k==="code"} className="w-full border p-2 rounded" placeholder={k.toUpperCase()} value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/>)}<label className="flex gap-2"><input type="checkbox" checked={form.active} onChange={e=>setForm({...form,active:e.target.checked})}/> Active</label><button className="bg-blue-600 text-white px-4 py-2 rounded">{editing?"Update":"Create"}</button>{editing&&<button type="button" onClick={()=>{setEditing(null);setForm(empty)}} className="ml-2 px-4 py-2 border rounded">Cancel</button>}</form>
            <form onSubmit={saveStock} className="bg-white p-6 rounded-xl shadow space-y-3"><h2 className="text-xl font-semibold">Manage Warehouse Stock</h2><select required className="w-full border p-2 rounded" value={selectedWarehouse} onChange={e=>setSelectedWarehouse(e.target.value)}><option value="">Select warehouse</option>{warehouses.map(w=><option key={w.id} value={w.id}>{w.name} ({w.code})</option>)}</select><select required className="w-full border p-2 rounded" value={productId} onChange={e=>setProductId(e.target.value)}><option value="">Select product</option>{products.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><input type="number" min="0" className="w-full border p-2 rounded" value={quantity} onChange={e=>setQuantity(e.target.value)}/><button className="bg-green-600 text-white px-4 py-2 rounded">Update Stock</button></form></div>
        <div className="bg-white rounded-xl shadow p-6 mb-8"><h2 className="text-xl font-semibold mb-4">Warehouses</h2><div className="overflow-auto"><table className="w-full"><thead><tr className="border-b text-left"><th className="p-2">Name</th><th>Code</th><th>Location</th><th>Status</th><th>Actions</th></tr></thead><tbody>{warehouses.map(w=><tr className="border-b" key={w.id}><td className="p-2">{w.name}</td><td>{w.code}</td><td>{w.city}, {w.state}</td><td>{w.active?"Active":"Inactive"}</td><td><button className="text-blue-600 mr-3" onClick={()=>{setEditing(w.id);setForm(w)}}>Edit</button><button className="text-red-600" onClick={()=>remove(w.id)}>Delete</button></td></tr>)}</tbody></table></div></div>
        <div className="bg-white rounded-xl shadow p-6"><h2 className="text-xl font-semibold mb-4">Warehouse Inventory</h2><div className="overflow-auto"><table className="w-full"><thead><tr className="border-b text-left"><th className="p-2">Warehouse</th><th>Product</th><th>Quantity</th><th>Reserved</th><th>Available</th></tr></thead><tbody>{inventory.map(i=><tr className="border-b" key={i.id}><td className="p-2">{i.warehouseName}</td><td>{i.productName}</td><td>{i.quantity}</td><td>{i.reservedQuantity}</td><td>{i.availableQuantity}</td></tr>)}</tbody></table></div></div>
    </div></div>;
}
